var fs=require("fs"),path=require("path"),util=require("util"),stream=require("stream"),net=require("net"),mkdirp=require("mkdirp"),async=require("async"),log=require("npmlog"),ssh2=require("ssh2"),shelljs=require("shelljs"),express=require("express"),http=require("http"),mkdirp=require("mkdirp"),request=require("request"),Validator=require("jsonschema").Validator,server=require("./server"),errMsgHndl=require("./error-handler"),appdata=require("./cli-appdata"),novacomusb=require("./novacom-usb");
(function(){function p(a,b,d){var c=null;if(0!==b||d)c=Error("Command '"+a+"' exited with code="+b+" (signal: "+d+")"),c.code=b,c.signal=d;return c}function q(){this.devices=[];this.deviceFileContent=null;l=new appdata;r=l.getPath()}var m={};"undefined"!==typeof module&&module.exports&&(module.exports=m);log.heading="novacom";log.level="warn";m.log=log;var h=path.resolve(process.env.HOME||process.env.USERPROFILE,".ssh"),r,l;m.Resolver=q;m.Resolver.prototype={load:function(a){var b=this;log.verbose("Resolver#load()");
async.waterfall([function(a){log.verbose("Resolver#load#_replaceBuiltinSshKey()");var b=path.join(__dirname,"webos_emul"),d=path.join(h,"webos_emul");fs.stat(b,function(c,e){c?"ENOENT"===c.code?setImmediate(a):setImmediate(a,c):fs.stat(d,function(c,f){c?"ENOENT"===c.code?mkdirp(h,function(c){shelljs.cp("-rf",b,h);fs.chmodSync(d,"0600");setImmediate(a)}):setImmediate(a,c):(e.mtime.getTime()>f.mtime.getTime()&&(shelljs.cp("-rf",b,h),fs.chmodSync(d,"0600")),setImmediate(a))}.bind(this))}.bind(this))}.bind(b),
function(a){var c=l.getDeviceList(!0);Array.isArray(c)?(log.silly("Resolver#load#_loadString()","inDevices:",c),async.forEach(c,function(a,c){async.series([b._loadOne.bind(b,a),b._addOne.bind(b,a)],c)},function(c,d){c?setImmdiate(a,c):(log.verbose("Resolver#load#_loadString()","devices:",b.devices),setImmediate(a))})):setImmediate(a,Error("Incorrect file format'"))}.bind(b),function(a){log.silly("Resolver#load#_loadUSBDevice()");async.waterfall([novacomusb.getDeviceList.bind(novacomusb,{appdir:r}),
function(a,d){async.forEach(a,function(a,c){async.series([b._loadOne.bind(b,a),b._addOne.bind(b,a)],c)},d)}],function(b,d){setImmediate(a,b)})}.bind(b)],function(d){d?setImmediate(a,d):(log.info("Resolver#load()","devices:",b.devices),setImmediate(a))})},_loadOne:function(a,b){log.silly("Resolver#_loadOne()","device:",a);"string"===typeof a.privateKey?(a.privateKeyName=a.privateKey,a.privateKey=new Buffer(a.privateKey,"base64"),setImmediate(b)):"object"===typeof a.privateKey&&"string"===typeof a.privateKey.openSsh?
(a.privateKeyName=a.privateKey.openSsh,async.waterfall([fs.readFile.bind(this,path.join(h,a.privateKey.openSsh),b),function(b,c){a.privateKey=b;setImmediate(c)}],function(d){d&&(log.verbose("Resolver#_loadOne()","Unable to find SSH private key named '"+a.privateKey.openSsh+"' from '"+h+" for '"+a.name+"'"),a.privateKey=void 0);setImmediate(b)})):"webospro"===typeof a.type?setImmediate(b,Error("Not implemented: go & grab the webOS Pro private key here")):(a.password||log.verbose("Resolver#_loadOne()",
"Regist privateKey : need to set a SSH private key in "+h+" for'"+a.name+"'"),a.privateKeyName=void 0,a.privateKey=void 0,setImmediate(b))},_addOne:function(a,b){if(!a.profile||!l.compareProfileSync(a.profile))return setImmediate(b);a.display={name:a.name,type:a.type,privateKeyName:a.privateKeyName,passphase:a.passphase,description:a.description,conn:a.conn||["ssh"],devId:a.id||null};a.username&&a.host&&a.port&&(a.display.addr="ssh://"+a.username+"@"+a.host+":"+a.port);for(var d in a)"display"!==
d&&(a.display[d]=a[d]);log.silly("Resolver#_addOne()","device:",a);this.devices=this.devices.filter(function(b){return b.name!==a.name});d=l.getCommandService();a.lunaSend=d[a.type].lunaSend;a.lunaAddr=d[a.type].lunaAddr;this.devices.push(a);setImmediate(b)},save:function(a,b){log.verbose("Resolver#save()","devicesData:",a);return l.setDeviceList(a,b)},list:function(a){log.verbose("Resolver#list()");setImmediate(a,null,this.devices.map(function(a){return a.display}))},setDefaultName:function(a,b){var d=
"string"===typeof a?a:a&&a.name;if(!d){d=this.devices.filter(function(a){return a.conn&&-1!==a.conn.indexOf("novacom")});if(1<d.length)return b(Error("multiple devices are connected by novacom, please specify target name."));d=0<d.length&&d[0].name?d[0].name:"emulator"}b(null,"name",d)},getDeviceBy:function(a,b,d){log.verbose("Resolver#getDeviceBy()","key:",a,"value:",b);var c=this.devices.filter(function(c){return c[a]&&c[a]===b});if(1>c.length)setImmediate(d,Error("No device matching '"+a+"'='"+
b+"'"));else if(log.verbose("Resolver#getDeviceBy()","devices:",c),"function"===typeof d)log.silly("Resolver#getDeviceBy()","async"),setImmediate(d,null,c[0]);else return log.silly("Resolver#getDeviceBy()","sync"),c[0]},getSshPrvKey:function(a,b){var d="string"===typeof a?a:a&&a.name;d?async.waterfall([this.getDeviceBy.bind(this,"name",d),function(a,b){log.info("Resolver#getSshPrvKey()","target.host:",a.host);var c="http://"+a.host+":9991/webos_rsa",d=a.name.replace(/(\s+)/gi,"_")+"_webos",e=path.join(h,
d);request.head(c,function(a,f,g){if(a||f&&200!==f.statusCode)return setImmediate(b,Error("Failed to get ssh private key"));log.info("Resolver#getSshPrvKey()#head","content-type:",f.headers["content-type"]);log.info("Resolver#getSshPrvKey()#head","content-length:",f.headers["content-length"]);request(c).pipe(fs.createWriteStream(e)).on("close",function(a){if(a)return setImmediate(b,Error("Failed to get ssh private key"));setImmediate(b,a,e,d)})})},function(a,b,d){log.info("Resolver#getSshPrvKey()",
"SSH Private Key:",a);console.log("SSH Private Key:",a);fs.chmodSync(a,"0600");setImmediate(d,null,b)}],b):setImmediate(b,Error("Need to select a device name to get Ssh Private Key"))},modifyDeviceFile:function(a,b,d){if(b.name){var c=l.getDeviceList(!0);if(Array.isArray(c)){if("add"==a){a=-1;for(idx in c){if(c[idx].name===b.name){setImmediate(d,Error("Existing Target Name"));return}c[idx].order>a&&(a=c[idx].order)}-1!=a&&(b.order=++a);for(key in b)"@DELETE@"===b[key]&&delete b[key];c=c.concat(b)}else if("remove"==
a){a=-1;for(idx in c)if(c[idx].name===b.name){a=c[idx].order||-1;break}if(-1!==idx){if(c[idx].name!==b.name)return setImmediate(d,Error("Please enter a correct device name!!"));if(c[idx].indelible&&!0===c[idx].indelible)return setImmediate(d,Error("this device should not be removed!!"));c.splice(idx,1);for(idx in c)c[idx].order>a&&c[idx].order--}}else if("modify"==a){var e=!1;c.forEach(function(a){a.name===b.name&&(e=!0,Object.keys(b).forEach(function(c){"@DELETE@"===b[c]?delete a[c]:a[c]=b[c]}))});
if(!1===e)return setImmediate(d,Error("Could not find a device named "+b.name))}else return setImmediate(d,Error("Unknown operator"));this.save(c,d)}else setImmediate(d,Error("Incorrect file format'"))}else setImmediate(d,Error("Incorrect target name"))}};m.Session=function(a,b){if("function"!==typeof b)throw Error("novacom.Session(): BUG next must be a common-js callback");log.info("novacom.Session()","opening session to '"+("string"===typeof a?a:a&&a.name)+"'");this.resolver=new q;async.waterfall([this.resolver.load.bind(this.resolver),
this.resolver.setDefaultName.bind(this.resolver,a),this.resolver.getDeviceBy.bind(this.resolver),this.checkConnection.bind(this),this.begin.bind(this)],b)};m.Session.prototype={checkConnection:function(a,b){var d=!1;if(a&&a.host&&a.port){var c=new net.Socket;c.setTimeout(2E3);var e=c.connect({host:a.host,port:a.port});e.on("connect",function(){d=!0;e.end();setImmediate(b,null,a)});e.on("error",function(a){e.destroy();setImmediate(b,errMsgHndl.changeErrMsg(a))});e.on("timeout",function(a){e.destroy();
d||setImmediate(b,errMsgHndl.changeErrMsg("Time out"))})}else setImmediate(b,null,a)},begin:function(a,b){function d(a){setImmediate(b,errMsgHndl.changeErrMsg(a),this)}function c(){log.verbose("Clear Session");e.end();setTimeout(function(){process.exit()},500)}log.verbose("Session#begin()","target:",a);var e=this;this.target=a||this.target;if(this.target.conn&&-1===this.target.conn.indexOf("ssh"))return setImmediate(b,null,this),this;if(!typeof this.target.privateKey&&!typeof this.target.password)return setImmediate(b,
Error("Private Key File or Password does not exist!!"));this.ssh||(this.forwardedPorts=[],this.ssh=new ssh2,this.ssh.on("connect",function(){log.verbose("Session#begin()","ssh session event: connected")}),this.ssh.on("ready",d.bind(this)),this.ssh.on("error",d.bind(this)),this.ssh.on("end",function(){log.verbose("Session#begin()","ssh session event: end")}),this.ssh.on("close",function(a){log.verbose("Session#begin()","ssh session event: close  (had_error:",a,")")}),this.target.readyTimeout=3E4,this.ssh.connect(this.target),
process.on("SIGHUP",c),process.on("SIGINT",c),process.on("SIGQUIT",c),process.on("SIGTERM",c),process.on("exit",function(a){c()}));return this},getDevice:function(){return this.target},end:function(){log.verbose("Session#end()","user-requested termination");this.ssh&&this.ssh.end();return this},_checkSftp:function(a){this.ssh.subsys("sftp",function(b,d){if(b)return setImmediate(a,b);d.once("data",function(b){if(b.toString().match(RegExp("sftp-server(.| )+not found","gi")))return b=Error("Unable to use sftp"),
b.code=4,setImmediate(a,b)})})},put:function(a,b,d){log.verbose("Session#put()","uploding into device:",b,"from host:",a);var c,e=this;log.verbose("Session#put()","sftpPut() :: start");e.sftpPut(a,b,function(f){f?(log.verbose(f),4===f.code||127===f.code?(log.verbose("Session#put()","sftp is not available, attempt transfering file via streamPut"),c=fs.createReadStream(a),e.streamPut(b,c,d)):(14===f.code&&(f=errMsgHndl.changeErrMsg("insufficient free space")),setImmediate(d,f))):(log.verbose("Session#put()",
"sftpPut() :: done"),setImmediate(d))})},streamPut:function(a,b,d){log.verbose("Session#streamPut()","streaming into device:"+a);this.run('/bin/cat > "'+a+'"',b,null,process.stderr,d)},sftpPut:function(a,b,d){log.verbose("Session#sftpPut()","host:"+a+" => device:"+b);var c=this;c._checkSftp(d);async.series({transfer:function(d){c.ssh.sftp(function(c,e){if(c)return setImmediate(d,c);var f=fs.createReadStream(a),g=e.createWriteStream(b);g.on("close",function(){e.end();setImmediate(d)});g.on("exit",
function(a,b){c=p("sftpPut",a,b);setImmediate(d,c)});g.on("error",function(a){log.verbose("Session#sftpPut()","error:",a);setImmediate(d,a)});f.pipe(g)})}},function(a){setImmediate(d,a)})},get:function(a,b,d){log.verbose("Session#get()","downloading into host:",b,"from target:",a);var c=this;log.verbose("Session#get()","sftpGet() :: start");c.sftpGet(a,b,function(e){e?(log.verbose(e),4===e.code||127===e.code?(log.verbose("Session#get()","sftp is not available, attempt transfering file via streamPut"),
os=fs.createWriteStream(b),c.streamGet(a,os,d)):setImmediate(d,e)):(log.verbose("Session#get()","sftpGet() :: done"),setImmediate(d))})},streamGet:function(a,b,d){log.verbose("Session#streamGet()","streaming from device:"+a);this.run("/bin/cat "+a,null,b,process.stderr,d)},sftpGet:function(a,b,d){log.verbose("Session#sftpGet()","target:"+a+" => host:"+b);var c=this;c._checkSftp(d);async.series({transfer:function(d){c.ssh.sftp(function(c,e){if(c)setImmediate(d,c);else{var f=e.createReadStream(a),g=
fs.createWriteStream(b);f.on("close",function(){e.end();setImmediate(d)});f.on("exit",function(a,b){c=p("sftpGet",a,b);setImmediate(d,c)});f.on("error",function(a){log.verbose("Session#sftpGet()","error:",a);setImmediate(d,a)});f.pipe(g)}})}},function(a){setImmediate(d,a)})},run:function(a,b,d,c,e){this.ssh?this.run_ssh(a,b,d,c,e):novacomusb.runDeviceCommand(this.target.id,a,b,d,c,e)},run_ssh:function(a,b,d,c,e){log.verbose("Session#run()","cmd="+a);if("function"!==typeof e)throw Error("BUG: 'next' is not a callback");
var f={},g={};d?d instanceof stream.Stream?(log.silly("Session#run()","stdout: stream"),f.stdout=d.write,g.stdout=d):d instanceof Function?(log.silly("Session#run()","stdout: function"),f.stdout=d):setImmediate(e,Error("Invalid novacom stdout: "+util.inspect(d))):(log.silly("Session#run()","stdout: none"),f.stdout=function(){});c?c instanceof stream.Stream?(log.silly("Session#run()","stderr: stream"),f.stderr=c.write,g.stderr=c):c instanceof Function?(log.silly("Session#run()","stderr: function"),
f.stderr=c):setImmediate(e,Error("Invalid novacom stderr: "+util.inspect(c))):(log.silly("Session#run()","stderr: none"),f.stderr=function(){});this.ssh.exec(a,function(k,n){log.verbose("Session#run()","exec cmd: "+a+", err:"+k);if(k)return setImmediate(e,k);n.on("data",function(a,b){b=b||"stdout";log.verbose("Session#run()","on data ("+b+")");f[b].bind(g[b])(a)}).stderr.on("data",function(a){log.verbose("Session#run()","on data (stderr)");f.stderr.bind(g.stderr)(a)});n.on("end",function(){log.verbose("Session#run()",
"event EOF from (cmd: "+a+")");d!==process.stdout&&d instanceof stream.Stream&&d.end();c!==process.stderr&&c instanceof stream.Stream&&c.end()});n.on("exit",function(b,c){log.verbose("Session#run()","event exit code="+b+", signal="+c+" (cmd: "+a+")");k=p(a,b,c);setImmediate(e,k)});n.on("close",function(){log.verbose("Session#run()","event close  (cmd: "+a+")");void 0===k&&setImmediate(e)});b&&(b.pipe(n),log.verbose("Session#run()","resuming input"))}.bind(this))},runNoHangup:function(a,b,d,c){this.ssh?
this.runNoHangup_ssh(a,b,d,c):novacomusb.runDeviceCommand(this.target.id,a,null,null,null,c)},runNoHangup_ssh:function(a,b,d,c){log.verbose("Session#runNoHangup()","cmd="+a);if(2>arguments.length)throw Error("BUG: 'next' is not a callback");for(arg in arguments)"undefined"===typeof arguments[arg]&&(delete arguments[arg],arguments.length--);switch(arguments.length){case 2:c=b;b=d=null;break;case 3:c=d,d=b,b=null}if("function"!==typeof c)throw Error("BUG: 'next' is not a callback");this.ssh.exec(a,
function(e,f){log.verbose("Session#run()","exec cmd: "+a+", err:"+e);if(e)return setImmediate(c,e);f.on("data",function(a,c){var d=Buffer.isBuffer(a)?a.toString():a;log.verbose("[Session#runNoHangup()#onData]",d);b&&b(a)}).stderr.on("data",function(a){var c=Buffer.isBuffer(a)?a.toString():a;log.verbose("Session#runNoHangup()#onData#stderr#",c);b&&b(a)});if(d)f.on("exit",function(b,c){log.verbose("Session#runNoHangup()","event exit code="+b+", signal="+c+" (cmd: "+a+")");e=p(a,b,c);d(e)});setImmediate(c)}.bind(this))},
forward:function(a,b,d,c){log.verbose("Session#forward()","devicePort:",a,"localPort:",b);var e=this,f=!1,g=null;"function"===typeof d?c=d:d&&(g=d);0!==b?0<e.forwardedPorts.indexOf({name:g,local:b,device:a})&&(f=!0):0<e.forwardedPorts.filter(function(b){return b.device===a&&b.name===g}).length&&(f=!0);if(f)return setImmediate(c);var k=net.createServer(function(c){log.info("Session#forward()","new client, localPort:",b);log.verbose("Session#forward()","new client, from: "+c.remoteAddress+":"+c.remotePort);
c.on("error",function(a){log.verbose("Session#forward()","inCnx::error, err:: "+a)});e.ssh.forwardOut("127.0.0.1",c.remotePort,"127.0.0.1",a,function(d,e){d?(console.log("Session#forward()","failed forwarding client localPort:",b,"(inCnx.remotePort:",c.remotePort,")=> devicePort:",a),log.warn("Session#forward()","failed forwarding client localPort:",b,"=> devicePort:",a),c.destroy()):(log.info("Session#forward()","connected, devicePort:",a),c.on("data",function(a){e.writable&&!0===e.writable&&!1===
e.write(a)&&c.pause()}),c.on("close",function(a){log.verbose("Session#forward()","inCnx::close, had_err:",a);e.destroy()}),e.on("drain",function(){c.resume()}),e.on("data",function(a){c.write(a)}),e.on("close",function(a){log.verbose("Session#forward()","outCnx::close, had_err:",a)}))})});e.ssh.on("close",function(){k.close()});try{var h;k.listen(b,null,function(){h=k.address().port;e.forwardedPorts.push({name:g,local:h,device:a});setImmediate(c)}.bind(this))}catch(t){setImmediate(c,t)}},getLocalPortByDevicePort:function(a){var b=
null;this.forwardedPorts.forEach(function(d){d.device===a&&(b=d.local)});return b},getLocalPortByName:function(a){var b=null;this.forwardedPorts.forEach(function(d){d.name===a&&(b=d.local)});return b},runHostedAppServer:function(a,b){server.runServer(a,0,function(a,c){c&&c.port&&this.setHostedAppServerPort(c.port);b(a)}.bind(this))},setHostedAppServerPort:function(a){this.hostedAppServerPort=a},getHostedAppServerPort:function(){return this.hostedAppServerPort}}})();
